Bai_tap_thuc_hanh/Bai_tap_thuc_hanh/Models/ErrorViewModel.cs
namespace Bai_tap_thuc_hanh.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Bai_tap_thuc_hanh/Bai_tap_thuc_hanh/Models/Product.cs
namespace Bai_tap_thuc_hanh.Models
{
    public class Product
    {
        public int Id { get; set; } 
        public string Name { get; set; }
        public string Image { get; set; }
        public decimal Price { get; set; }  

        public List <Product> GetProductsList()
        {
            return new List<Product>
            {
                new Product { Id = 1, Name = "Nồi cơm điện cao tần Nagakawa NAG0102", Image = "/images/products/noi com.jpg" },
                new Product { Id = 2, Name = "Nồi cơm điện cao tần Nagakawa NAG0102", Image = "/images/products/noi com.jpg"},
                new Product { Id = 3, Name = "Nồi cơm điện cao tần Nagakawa NAG0102", Image = "/images/products/noi com.jpg"},
            };
        }

        public Product GetProductById(int id)
        {
            return GetProductsList().FirstOrDefault(p => p.Id == id);
        }
    }
}

Bai_tap_thuc_hanh/Bai_tap_thuc_hanh/Controllers/HomeController.cs
using System.Diagnostics;
using Bai_tap_thuc_hanh.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bai_tap_thuc_hanh.Controllers
{
    public class HomeController : Controller
    {
        protected Product product = new Product();

        public IActionResult Index()
        {
            var products = product.GetProductsList();
            return View(products);
        }

    }
}

Bai_tap_thuc_hanh/Bai_tap_thuc_hanh/ViewComponents/HotProductViewComponent.cs
using Bai_tap_thuc_hanh.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bai_tap_thuc_hanh.ViewComponents
{
    public class HotProductViewComponent : ViewComponent
    {
        protected Product product = new Product();
        public IViewComponentResult Invoke()
        {
            var hotProducts = product.GetProductsList();
            return View(hotProducts);
        }
    }
}

Bai_tap_thuc_hanh/Bai_tap_thuc_hanh/Views/Home/Index.cshtml
@model List<Bai_tap_thuc_hanh.Models.Product>;
@{
    ViewData["Title"] = "Home Page";
}

<div class="box-title">Sản phẩm mới nhất</div>
<div class="product-list">
    @foreach (var p in Model)
    {
        <div class="product">
            <img src="@p.Image" alt="@p.Name" />
            <p>@p.Name</p>
        </div>
    }
</div>

<div class="box-title">Sản phẩm hot</div>
@await Component.InvokeAsync("HotProduct");

Bai_tap_thuc_hanh/Bai_tap_thuc_hanh/Views/Shared/Components/HotProduct/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    @model List<Bai_tap_thuc_hanh.Models.Product>;

    <div class="hot-products">
        @foreach (var p in Model)
        {
            <div class="product">
                <img src="@p.Image" alt="@p.Name" />
                <p>@p.Name</p>
            </div>
        }
    </div>
}

Bai_tap_thuc_hanh/Bai_tap_thuc_hanh/Views/Shared/_Category.cshtml
<div class="category">
    <h3>Danh mục sản phẩm</h3>
    <ul>
        <li>Áo dài</li>
        <li>Áo khoác</li>
        <li>Túi xách</li>
        <li>Ví</li>
        <li>Giày</li>
        <li>Thắt lưng da</li>
        <li>Tủ lạnh</li>
        <li>TiVi</li>
        <li>Quạt điện</li>
        <li>Lò sưởi</li>
    </ul>
    <div class="banner">
        <img src="~/images/products/quang cao.jpg" alt="Khuyến mãi" />
    </div>
</div>

Bai_tap_thuc_hanh/Bai_tap_thuc_hanh/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Demo Lab</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="navbar">
        <h3>Demo Lab</h3>
        <a class="active" href="/">Trang chủ</a>
        <a href="/Home/About">Giới thiệu</a>
        <a href="/Home/Contact">Liên hệ</a>
        <a href="/Home/Product">Sản phẩm</a>
    </div>

    <div class="container">
        <div class="sidebar">
            @Html.Partial("_Category")
        </div>
        <div class="main-content">
            @RenderBody()
        </div>
    </div>

    <footer>
        <div class="footer-left">
            <h3>GIỚI THIỆU</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
        <div class="footer-right">
            <h3>LIÊN HỆ</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
    </footer>
</body>
</html>